pipeline {
  agent any
  
  environment{
		DOCKERHUB_CREDENTIALS=credentials('dockerhub-alpineinfo-token')
	}
  
  stages {
    stage('Build') {
      steps {
        sh "docker build -t serbgn/node-alpine-info:build-${BUILD_NUMBER} -t serbgn/node-alpine-info:latest ./ci-pipeline"
        }
      }
    stage('Login') {
      steps {
        sh '''
        echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
        '''
        }
      }
    stage('Push') {
      steps {
        sh """
        docker image push -a serbgn/node-alpine-info
        """
        }
      }
  }
  post{
    always{
      sh 'docker logout'
    }
  cleanup{
   sh 'docker image rm serbgn/node-alpine-info:build-${BUILD_NUMBER}'	
   sh 'docker image rm serbgn/node-alpine-info:latest'	
  }
  }
}
