pipeline {
  agent any
  
  environment{
		DOCKERHUB_CREDENTIALS=credentials('dockerhub-alpineinfo-token')
	}
  
  stages {
    stage('Build') {
      steps {
        sh "docker build -t node-alpine-info:${BUILD_NUMBER} -t node-alpine-info:latest ./ci-pipeline"
        }
      }
    stage('Login') {
      steps {
        sh '''
        echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
        '''
        }
      }
    stage('Push') {
      steps {
        sh '''
        docker image push --all-tags node-alpine-info
        '''
        }
      }
  }
  post{
    always{
      sh 'docker logout'
    }
  }
}
